=== shishirshobhan/Fenwick-Store/catalog_20048506.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Store">
    <xs:complexType>
      <xs:sequence>
      <xs:element type="xs:string" name="Logo"/>
        <xs:element type="xs:string" name="Store_Name"/>
         <xs:element type="xs:string" name="Store_Motto" minOccurs="0"/>
         <xs:element type="xs:string" name="Store_Description"/>
        <xs:element name="Store_Address" />
        <xs:element name="Store_Contact">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Mobile">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="mobile_restriction">
                      <xs:attribute type="xs:byte" name="Country_Code"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Landline">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="landline_restriction">
                      <xs:attribute type="xs:byte" name="State_Code"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:anyURI" name="Store_Website"/>
        <xs:element name="Mail">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Postal_Address" minOccurs="0"/>
              <xs:element name="E-mail">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[^@]+@[^\.]+\..+"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Gift_Cards">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Gift_Card" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Code_Number" minOccurs="0"/>
                    <xs:element name="Card_Validity">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:date" name="Card_Activation_Date"/>
                          <xs:element type="xs:date" name="Card_Expired_Date"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Valid_Places">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="description"/>
                          <xs:element type="xs:string" name="Place"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Card_Cost">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="currency" use="optional">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="Pound"></xs:enumeration>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="Card_Owner_Name" minOccurs="0"/>
                    <xs:element type="xs:string" name="Card_owner_Address" minOccurs="0"/>
                    <xs:element name="Discount_Voucher">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Discount_Percentage"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="Discount_Type" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" use="optional">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="Digital"/>
                        <xs:enumeration value="Physical"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="mobile_restriction">
    <xs:restriction base="xs:string">
      <xs:pattern value="44[0-9]-[0-9]{3}-[0-9]{4}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="landline_restriction">
    <xs:restriction base="xs:string">
      <xs:pattern value="020-[0-9]{3}-[0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== shishirshobhan/Fenwick-Store/catalog_20048506.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="catalog_20048506.css"?>
<Store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20048506.xsd">
	<Logo/>
	<Store_Name>Fenwick Department Store</Store_Name>
	<Store_Motto>Store never sleeps</Store_Motto>
	<Store_Description>Fenwick (/ˈfɛnɪk/) is an independent chain of department stores in the United Kingdom.
	</Store_Description>
	<Store_Address >Addle Street,London,5208</Store_Address>
	<Store_Contact>
		<Mobile Country_Code="44">441-254-8928</Mobile>
		<Landline State_Code="020">020-445-892</Landline>
	</Store_Contact>
	<Store_Website>http://www.fenwickstore.com</Store_Website>
	<Mail>
		<Postal_Address>Postal code: East London</Postal_Address>
		<E-mail>fenwickstore@gmail.com</E-mail>
	</Mail>
	<Gift_Cards>
		<Gift_Card type="Digital">
			<Code_Number>Code Number: 100</Code_Number>
			<Card_Validity>
				<Card_Activation_Date>2021-04-28</Card_Activation_Date>
				<Card_Expired_Date>2022-04-28</Card_Expired_Date>
			</Card_Validity>

			<Valid_Places>
				<description>Places where this card is valid</description>
				<Place>Retail Store, Resturants, Gas station</Place>
			</Valid_Places>

			<Card_Cost currency="Pound">Cost: 150</Card_Cost>
			<Card_Owner_Name>Stephen Houdina</Card_Owner_Name>
			<Card_owner_Address>Springfield Road</Card_owner_Address>
			<Discount_Voucher Discount_Type="Percentage">
				<Discount_Percentage>Discount Percent: 15</Discount_Percentage>
			</Discount_Voucher>
		</Gift_Card>

		<Gift_Card type="Digital">
			<Code_Number>Code Number: 110</Code_Number>
			<Card_Validity>
				<Card_Activation_Date>2021-05-28</Card_Activation_Date>
				<Card_Expired_Date>2022-05-28</Card_Expired_Date>
			</Card_Validity>

			<Valid_Places>
				<description>Places where this card is valid</description>
				<Place>Retail Store, Resturants, Gas station</Place>
			</Valid_Places>

			<Card_Cost currency="Pound">Cost: 150</Card_Cost>
			<Card_Owner_Name>Charles Darwin</Card_Owner_Name>
			<Card_owner_Address>Grange Road</Card_owner_Address>
			<Discount_Voucher Discount_Type="Percentage">
				<Discount_Percentage>Discount Percent: 15</Discount_Percentage>
			</Discount_Voucher>
		</Gift_Card>
		<Gift_Card type="Digital">
			<Code_Number>Code Number: 120</Code_Number>
			<Card_Validity>
				<Card_Activation_Date>2021-06-28</Card_Activation_Date>
				<Card_Expired_Date>2022-06-28</Card_Expired_Date>
			</Card_Validity>

			<Valid_Places>
				<description>Places where this card is valid</description>
				<Place>Retail Store, Resturants, Gas station</Place>
			</Valid_Places>

			<Card_Cost currency="Pound">Cost: 150</Card_Cost>
			<Card_Owner_Name>Robert Carlos</Card_Owner_Name>
			<Card_owner_Address>Highfield Road</Card_owner_Address>
			<Discount_Voucher Discount_Type="Percentage">
				<Discount_Percentage>Discount Percent: 15</Discount_Percentage>
			</Discount_Voucher>
		</Gift_Card>

		<Gift_Card type="Physical">
			<Card_Validity>
				<Card_Activation_Date>2021-07-28</Card_Activation_Date>
				<Card_Expired_Date>2022-07-28</Card_Expired_Date>
			</Card_Validity>

			<Valid_Places>
				<description>Places where this card is valid</description>
				<Place>Retail Store, Resturants, Gas station</Place>
			</Valid_Places>

			<Card_Cost currency="Pound">Cost: 200</Card_Cost>
			<Card_Owner_Name>Karim Benzema</Card_Owner_Name>
			<Card_owner_Address>Queen Street</Card_owner_Address>
			<Discount_Voucher Discount_Type="Percentage">
				<Discount_Percentage>Discount Percent: 10</Discount_Percentage>
			</Discount_Voucher>
		</Gift_Card>

		<Gift_Card type="Physical">
			<Card_Validity>
				<Card_Activation_Date>2021-08-28</Card_Activation_Date>
				<Card_Expired_Date>2022-08-28</Card_Expired_Date>
			</Card_Validity>

			<Valid_Places>
				<description>Places where this card is valid</description>
				<Place>Retail Store, Resturants, Gas station</Place>
			</Valid_Places>

			<Card_Cost currency="Pound">Cost: 200</Card_Cost>
			<Card_Owner_Name>Gareth Bale</Card_Owner_Name>
			<Discount_Voucher Discount_Type="Percentage">
				<Discount_Percentage>Discount Percent: 10</Discount_Percentage>
			</Discount_Voucher>
		</Gift_Card>

		<Gift_Card type="Physical">
			<Card_Validity>
				<Card_Activation_Date>2021-09-28</Card_Activation_Date>
				<Card_Expired_Date>2022-09-28</Card_Expired_Date>
			</Card_Validity>

			<Valid_Places>
				<description>Places where this card is valid</description>
				<Place>Retail Store, Resturants</Place>
			</Valid_Places>

			<Card_Cost currency="Pound">Cost: 200</Card_Cost>
			<Card_owner_Address>Main Road</Card_owner_Address>
			<Discount_Voucher Discount_Type="Percentage">
				<Discount_Percentage>Discount Percent: 10</Discount_Percentage>
			</Discount_Voucher>
		</Gift_Card>
	</Gift_Cards>
</Store>
